SSH:
  keys:
    private-key: /home/foo/.ssh/id_rsa
    public-key:  /home/foo/.ssh/id_rsa.pub
Servers:
  server1:
    host: server1.example.com
    port: 22
    user: bar
    commands:
      - 'cd /etc && pwd'
      - 'cat /etc/hosts'
  server2:
    host: server2.example.com
    port: 22
    user: foo
    commands:
      - 'touch test.txt'
